2025-05-14 10:04:17,040: root: INFO: MLTrader : Executing the initialize lifecycle method
2025-05-14 10:04:18,711: root: INFO: Current backtesting datetime 2023-12-15 08:30:00-05:00
2025-05-14 10:04:18,712: root: INFO: MLTrader : Executing the before_market_opens lifecycle method
2025-05-14 10:04:18,713: root: INFO: Current backtesting datetime 2023-12-15 09:30:00-05:00
2025-05-14 10:04:18,713: root: INFO: MLTrader : Executing the before_starting_trading lifecycle method
2025-05-14 10:04:18,714: root: INFO: [34mMLTrader : Executing the on_trading_iteration lifecycle method at 2025-05-14 10:04:18[0m
2025-05-14 10:04:18,714: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2025-05-14 10:04:18,723: root: WARNING: quote is not implemented for YahooData, but USD was passed as the quote
2025-05-14 10:04:18,723: root: ERROR: Strategy.create_order() got an unexpected keyword argument 'type'
2025-05-14 10:04:18,725: root: ERROR: Traceback (most recent call last):
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 819, in run
    self._run_trading_session()
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 770, in _run_trading_session
    self._on_trading_iteration()
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 286, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 310, in func_output
    result = func_input(self, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 86, in func_output
    return func_input(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/strategies/strategy_executor.py", line 388, in _on_trading_iteration
    on_trading_iteration()
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/tools/decorators.py", line 62, in func_output
    frame, result = call_function_get_frame(func_input, *args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott.atkinson/anaconda3/envs/reinfin-env/lib/python3.11/site-packages/lumibot/tools/decorators.py", line 30, in call_function_get_frame
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/scott.atkinson/src/reinfin/reinfin/tradingbot.py", line 34, in on_trading_iteration
    order = self.create_order(
            ^^^^^^^^^^^^^^^^^^
TypeError: Strategy.create_order() got an unexpected keyword argument 'type'

2025-05-14 10:04:18,726: root: INFO: MLTrader : Executing the on_bot_crash event method
2025-05-14 10:04:18,731: backtest_stats: INFO: Backtest took 0:00:01.691721 for a speed of 0.000
2025-05-14 10:04:18,731: root: WARNING: Cannot plot returns because the strategy returns are missing
2025-05-14 10:04:18,819: root: WARNING: Cannot create a tearsheet because the strategy returns are missing
